POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "55-55-5555555"
}

###
GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jason"
}
###
GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jason",
    "number": "55-55-5555555"
}

###
GET http://localhost:3001/api/persons